server:
    port: 8013
spring:
    application:
        name: es-demo
    data:
        elasticsearch:
            cluster-name: docker-cluster
            cluster-nodes: 127.0.0.1:9300
    datasource:
        url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: dev
        password: dev
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: false
        hibernate:
            ddl-auto: update